services:
  - type: web
    name: reproductor-musica
    env: node
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: SESSION_SECRET
        sync: false
    healthCheckPath: /
    autoDeploy: true 