services:
  - type: web
    name: reproductor-musica
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
    healthCheckPath: /
    autoDeploy: true
    buildFilter:
      paths:
        - package.json
        - package-lock.json
        - server.js
        - routes/**
        - Modelo/**
        - public/** 